@DirectoryChangeDetector_HostAddress = http://localhost:5281

POST {{DirectoryChangeDetector_HostAddress}}/api/v1/analyze
Content-Type: application/json

{
  "path": "C:\\some\\absolute\\path"
}

###
